### ISSUE TITLE
Ignoring Preflight check for small infrastructure guys

### ISSUE THREAD

**Issue by zmmdv** [caermeglaeddyv/ansible-roles#1]
Hello. Please add to your playbook ignoring Kubernetes preflight checks. For people with small resource pool. Thank you for your project and time wasting in such tough think as kubernetes and ansible.

**Comment by caermeglaeddyv** [comment]
Hi, @zmmdv 
I will take a time and improve "kubernetes" role to add the functionality you needed
Thnx a lot for checking this project out!

**Comment by zmmdv** [comment]
> Hi, @zmmdv
> I will take a time and improve "kubernetes" role to add the functionality you needed
> Thnx a lot for checking this project out!

thanks for your attention to detail, and a quick response great job from great people. Also if you can add one big README file for all roles and their ways will be more easier to find what newbees need  Hope more project and more roles will come soon!
