### ISSUE TITLE
Etcd helth check issue

### ISSUE THREAD

**Issue by zmmdv** [caermeglaeddyv/ansible-roles#2]
Hello. First off, thanks for the highly available cluster guide you wrote. I used your roles. But I wanted to raise my cluster on the latest version that Kubernetes has. I'm having problems with etcd. The problem is related to the change in syntax when checking health of etcd machines. Thanks for the work you've done!

**Comment by caermeglaeddyv** [comment]
Hello, @zmmdv !
Thank you for using roles and reporting issues!
As you know, for now roles support only Kubenetes version 1.14.1-1.15.10, and that issue with etcd health check is related to different versions of etcd used in different versions of Kubeadm (depends on k8s version which will be installed).
So health check of new version of etcd must be done using, for example, the same version of etcd containers, as done in Kubernetes documentation ("8. Optional: Check the cluster health" - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) and as done in 'etcd' role.
But the thing is, that new versions of etcd uses different syntax for keys used in health check. And when i'll be adding support for new versions of Kubernetes, i will handle that anyway.
For now you can use health check provided with documentation as workaround.
Again, thank you a lot for your interest!
